kind: pipeline
name: gcc-cmake
platform:
  os: linux
  arch: arm
trigger:
  branch:
  - master
  event:
  - push
  - cron

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: gcc-cmake.docker
    username: viers
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: viers/gcc-cmake
    tags:
      - latest

---
kind: pipeline
name: build-agent
trigger:
  branch:
  - master
  event:
  - push
  - cron

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: build-agent.docker
    username: viers
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: viers/build-agent
    tags:
      - latest

---
kind: pipeline
name: qt-static
platform:
  os: linux
  arch: arm
trigger:
  branch:
  - master
  event:
  - push
  - cron

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: qt-static.docker
    username: viers
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: viers/qt-static
    tags:
      - latest
