kind: pipeline
name: build-agent
trigger:
  branch:
  - master
  event:
  - cron

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: build-agent/build-agent.docker
    username: viers
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: viers/build-agent
    tags:
      - latest



---
kind: pipeline
name: gcc-cmake
platform:
  os: linux
  arch: arm
trigger:
  branch:
  - master
  event:
  - cron

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: qt-static/gcc-cmake.docker
    username: viers
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: viers/gcc-cmake
    tags:
      - latest

- name: create-tag
  image: drone/git:latest
  environment:
    GHUB_TOKEN:
      from_secret: GHUB_TOKEN
  commands:
  - ./update_tag.sh gcc-cmake-ready

---
kind: pipeline
name: qt-static-deps
platform:
  os: linux
  arch: arm
trigger:
  branch:
  - master
  event:
  - tag
  ref:
  - refs/tags/gcc-cmake-ready

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: qt-static/qt-deps.docker
    username: viers
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: viers/qt-static
    tags:
      - internal-deps

- name: create-tag
  image: drone/git:latest
  environment:
    GHUB_TOKEN:
      from_secret: GHUB_TOKEN
  commands:
  - ./update_tag.sh qt-deps-ready

---
kind: pipeline
name: qt-static-build
platform:
  os: linux
  arch: arm
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: qt-static/qt-static.docker
    username: viers
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: viers/qt-static
    tags:
      - dev

---
kind: pipeline
name: qt-experimental
platform:
  os: linux
  arch: arm
trigger:
  branch:
  - master
  event:
  - crone

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: qt-static/qt-tmp.docker
    username: viers
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: viers/qt-static
    tags:
      - dev
