kind: pipeline
name: gcc-cmake-arm32
platform:
  os: linux
  arch: arm
trigger:
  branch:
  - master
  event:
  - cron
  - push

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: dockerfiles/gcc-cmake.docker
    username: viers
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: viers/gcc-cmake
    tags:
      - latest-arm32

- name: create-tag
  image: drone/git:latest
  environment:
    GHUB_TOKEN:
      from_secret: GHUB_TOKEN
  commands:
  - ./update_tag.sh gcc-cmake-arm32

---
kind: pipeline
name: gcc-cmake-amd64
trigger:
  branch:
  - master
  event:
  - cron
  - push

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: dockerfiles/gcc-cmake.docker
    username: viers
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: viers/gcc-cmake
    tags:
      - latest-amd64
      - latest

- name: create-tag
  image: drone/git:latest
  environment:
    GHUB_TOKEN:
      from_secret: GHUB_TOKEN
  commands:
  - ./update_tag.sh gcc-cmake-amd64

---
kind: pipeline
name: build-agent-amd64
trigger:
  branch:
  - master
  event:
  - tag
  ref:
  - refs/tags/gcc-cmake-amd64

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: dockerfiles/build-agent.docker
    username: viers
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: viers/build-agent
    tags:
      - latest
      - latest-amd64

---
kind: pipeline
name: qt-static-arm32
platform:
  os: linux
  arch: arm
trigger:
  branch:
  - master
  event:
  - tag
  ref:
  - refs/tags/gcc-cmake-arm32

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: dockerfiles/qt-static.docker
    username: viers
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: viers/qt-static
    tags:
      - latest
      - latest-arm32
