FROM ubuntu:18.04
ENTRYPOINT ["/bin/bash"]

RUN \
    apt -y update && \
    apt -y upgrade && \
    apt -y install \
        git \
        && \
    apt -y autoremove && \
    apt -y autoclean && \
    apt -y clean && \
    rm -rf /var/lib/apt/lists/* && \
    exit 0
